apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
{{- if .Values.namespaceLabels }}
  labels:
{{- with .Values.namespaceLabels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
