apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
{{ include "gatekeeper.labels" . | indent 4 }}
{{- with .Values.namespaceLabels }}
{{ toYaml . | indent 4 }}
{{- end }}