name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Helm Deps
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo add gatekeeper https://open-policy-agent.github.io/gatekeeper/charts
          helm repo add istio https://istio-release.storage.googleapis.com/charts
          helm repo add argo https://argoproj.github.io/argo-helm

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"